name: Flutter

on:
  pull_request:
    branches: [ master ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter analyze

  #test:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: subosito/flutter-action@v2
  #      with:
  #        channel: 'stable'
  #    - run: flutter test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk